### ISSUE TITLE
Validate-vat Error: Failed to parseField countryCode - update to 0.8.0 required

### ISSUE THREAD

**Issue by Capaman** [valeriansaliou/node-sales-tax#45]
I'm getting this error:

Error: Failed to parseField countryCode
    at parseField (/project/node_modules/validate-vat/lib/index.js:53:15)
    at parseSoapResponse (/project/node_modules/validate-vat/lib/index.js:67:22)
    at IncomingMessage.<anonymous> (/project/node_modules/validate-vat/lib/index.js:108:18)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  soapMessage: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><soap:Fault><faultcode>soap:Server</faultcode><faultstring>The given SOAPAction urn:ec.europa.eu:taxud:vies:services:checkVat/checkVat does not match an operation.</faultstring></soap:Fault></soap:Body></soap:Envelope>'
}

... when I try to validate a tax number:

salesTax.validateTaxNumber("FR", "FR50833085806")
  .then((isValid) => {
        // ...
  })
  .catch(function(error){
	console.log('error:');
	console.log(error);                
  });
})

It used to work fine. Seems like to be the same issue as this: https://github.com/viruschidai/validate-vat/issues/46

Can you update validate-vat to the latest?! 0.8.0

**Comment by valeriansaliou** [comment]
Thanks. Released `v2.4.0` w/ a fix.
